// test_rolling_cross_validate_pandas.cpp — Cross-validate all 18 rolling operators against pandas reference
//
// Reference values generated by: python3 scripts/gen_rolling_ref.py
// Test data: [1..10, 10..1] (20 elements)
#include <gtest/gtest.h>
#include <cmath>
#include <cstdint>
#include <limits>

#include "quantcore/core/Types.h"
#include "quantcore/operators/RollingOperator.h"
#include "quantcore/operators/rolling/RollingDiff.h"
#include "quantcore/operators/rolling/RollingEma.h"
#include "quantcore/operators/rolling/RollingArgMax.h"
#include "quantcore/operators/rolling/RollingArgMin.h"
#include "quantcore/operators/rolling/RollingKurt.h"
#include "quantcore/operators/rolling/RollingMax.h"
#include "quantcore/operators/rolling/RollingMean.h"
#include "quantcore/operators/rolling/RollingMedian.h"
#include "quantcore/operators/rolling/RollingMin.h"
#include "quantcore/operators/rolling/RollingMul.h"
#include "quantcore/operators/rolling/RollingQuantile.h"
#include "quantcore/operators/rolling/RollingRank.h"
#include "quantcore/operators/rolling/RollingSkew.h"
#include "quantcore/operators/rolling/RollingStd.h"
#include "quantcore/operators/rolling/RollingSum.h"
#include "quantcore/operators/rolling/RollingVar.h"
#include "quantcore/operators/rolling/RollingShift.h"
#include "quantcore/operators/rolling/RollingSma.h"

using namespace quantcore;

// ============================================================
// Reference data — auto-generated from pandas via gen_rolling_ref.py
// ============================================================

static constexpr std::size_t kN = 20;
static const double kInput[] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1};

#define NN std::numeric_limits<double>::quiet_NaN()

// sum(window=3)
static const double kSumW3[] = {NN, NN, 6, 9, 12, 15, 18, 21, 24, 27, 29, 29, 27, 24, 21, 18, 15, 12, 9, 6};
// sum(window=5)
static const double kSumW5[] = {NN, NN, NN, NN, 15, 20, 25, 30, 35, 40, 44, 46, 46, 44, 40, 35, 30, 25, 20, 15};
// mean(window=3)
static const double kMeanW3[] = {NN, NN, 2, 3, 4, 5, 6, 7, 8, 9, 9.66666666666667, 9.66666666666667, 9, 8, 7, 6, 5, 4, 3, 2};
// var(window=3)
static const double kVarW3[] = {NN, NN, 0.666666666666667, 0.666666666666667, 0.666666666666667, 0.666666666666667, 0.666666666666667, 0.666666666666667, 0.666666666666667, 0.666666666666667, 0.222222222222222, 0.222222222222222, 0.666666666666667, 0.666666666666667, 0.666666666666667, 0.666666666666667, 0.666666666666667, 0.666666666666667, 0.666666666666667, 0.666666666666667};
// std(window=3)
static const double kStdW3[] = {NN, NN, 0.816496580927726, 0.816496580927726, 0.816496580927726, 0.816496580927726, 0.816496580927726, 0.816496580927726, 0.816496580927726, 0.816496580927726, 0.471404520791032, 0.471404520791032, 0.816496580927726, 0.816496580927726, 0.816496580927726, 0.816496580927726, 0.816496580927726, 0.816496580927726, 0.816496580927726, 0.816496580927726};
// max(window=3)
static const double kMaxW3[] = {NN, NN, 3, 4, 5, 6, 7, 8, 9, 10, 10, 10, 10, 9, 8, 7, 6, 5, 4, 3};
// min(window=3)
static const double kMinW3[] = {NN, NN, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 8, 7, 6, 5, 4, 3, 2, 1};
// median(window=3)
static const double kMedianW3[] = {NN, NN, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 9, 8, 7, 6, 5, 4, 3, 2};
// median(window=4)
static const double kMedianW4[] = {NN, NN, NN, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5, 9.5, 9.5, 8.5, 7.5, 6.5, 5.5, 4.5, 3.5, 2.5};
// mul(window=3)
static const double kMulW3[] = {NN, NN, 6, 24, 60, 120, 210, 336, 504, 720, 900, 900, 720, 504, 336, 210, 120, 60, 24, 6};
// argmax(window=3)
static const double kArgmaxW3[] = {NN, NN, 2, 2, 2, 2, 2, 2, 2, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0};
// argmin(window=3)
static const double kArgminW3[] = {NN, NN, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2};
// skew(window=5)
static const double kSkewW5[] = {NN, NN, NN, NN, 0, 0, 0, 0, 0, 0, -0.363173474419432, -0.343621596744543, -0.343621596744543, -0.363173474419432, 0, 0, 0, 0, 0, 0};
// kurt(window=5)
static const double kKurtW5[] = {NN, NN, NN, NN, -1.3, -1.3, -1.3, -1.3, -1.3, -1.3, -1.3719723183391, -1.1530612244898, -1.1530612244898, -1.3719723183391, -1.3, -1.3, -1.3, -1.3, -1.3, -1.3};
// rank(window=3)
static const double kRankW3[] = {NN, NN, 1, 1, 1, 1, 1, 1, 1, 1, 0.833333333333333, 0.333333333333333, 0.333333333333333, 0.333333333333333, 0.333333333333333, 0.333333333333333, 0.333333333333333, 0.333333333333333, 0.333333333333333, 0.333333333333333};
// quantile_q25(window=4)
static const double kQuantileQ25W4[] = {NN, NN, NN, 1.75, 2.75, 3.75, 4.75, 5.75, 6.75, 7.75, 8.75, 9, 8.75, 7.75, 6.75, 5.75, 4.75, 3.75, 2.75, 1.75};
// quantile_q50(window=4)
static const double kQuantileQ50W4[] = {NN, NN, NN, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5, 9.5, 9.5, 8.5, 7.5, 6.5, 5.5, 4.5, 3.5, 2.5};
// quantile_q75(window=4)
static const double kQuantileQ75W4[] = {NN, NN, NN, 3.25, 4.25, 5.25, 6.25, 7.25, 8.25, 9.25, 10, 10, 10, 9.25, 8.25, 7.25, 6.25, 5.25, 4.25, 3.25};
// ema(span=5)
static const double kEmaW5[] = {NN, NN, NN, NN, 3.39506172839506, 4.26337448559671, 5.17558299039781, 6.11705532693187, 7.07803688462125, 8.0520245897475, 8.70134972649833, 8.80089981766556, 8.53393321177704, 8.02262214118469, 7.3484147607898, 6.56560984052653, 5.71040656035102, 4.80693770690068, 3.87129180460045, 2.9141945364003};
// sma(window=3)
static const double kSmaW3[] = {NN, NN, 2, 3, 4, 5, 6, 7, 8, 9, 9.66666666666667, 9.66666666666667, 9, 8, 7, 6, 5, 4, 3, 2};
// diff(n=3)
static const double kDiffW3[] = {NN, NN, NN, 3, 3, 3, 3, 3, 3, 3, 2, 0, -2, -3, -3, -3, -3, -3, -3, -3};
// shift(n=3)
static const double kShiftW3[] = {NN, NN, NN, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 9, 8, 7, 6, 5, 4};

#undef NN

// ============================================================
// Helpers
// ============================================================

static void expectDoubleNanEq(double a, double b, const char* label, std::size_t i) {
    if (std::isnan(a)) {
        EXPECT_TRUE(std::isnan(b)) << label << " at i=" << i << ": Expected NaN, got " << b;
    } else if (std::isnan(b)) {
        EXPECT_TRUE(std::isnan(a)) << label << " at i=" << i << ": Expected " << a << ", got NaN";
    } else {
        EXPECT_NEAR(a, b, 1e-12) << label << " at i=" << i << ": Values differ";
    }
}

// ============================================================
// Test fixture
// ============================================================

class RollingOpPandasCrossValidate : public ::testing::Test {
protected:
    template <typename Op, typename... Args>
    void check(const double* ref, const char* label, Args&&... args) {
        Op op(std::forward<Args>(args)...);
        double output[kN];
        op.evaluate(ColView<double>(kInput, kN), output);
        for (std::size_t i = 0; i < kN; ++i) {
            expectDoubleNanEq(output[i], ref[i], label, i);
        }
    }
};

// ============================================================
// Tests — one per operator, grouped by category
// ============================================================

// --- Window statistics ---
TEST_F(RollingOpPandasCrossValidate, RollingSum)   { check<RollingSumOp>(kSumW3, "rolling_sum(w=3)", 3); }
TEST_F(RollingOpPandasCrossValidate, RollingMean)  { check<RollingMeanOp>(kMeanW3, "rolling_mean(w=3)", 3); }
TEST_F(RollingOpPandasCrossValidate, RollingVar)   { check<RollingVarOp>(kVarW3, "rolling_var(w=3)", 3); }
TEST_F(RollingOpPandasCrossValidate, RollingStd)   { check<RollingStdOp>(kStdW3, "rolling_std(w=3)", 3); }
TEST_F(RollingOpPandasCrossValidate, RollingMax)   { check<RollingMaxOp>(kMaxW3, "rolling_max(w=3)", 3); }
TEST_F(RollingOpPandasCrossValidate, RollingMin)   { check<RollingMinOp>(kMinW3, "rolling_min(w=3)", 3); }
TEST_F(RollingOpPandasCrossValidate, RollingMedian) {
    check<RollingMedianOp>(kMedianW3, "rolling_median(w=3)", 3);
    check<RollingMedianOp>(kMedianW4, "rolling_median(w=4)", 4);
}
TEST_F(RollingOpPandasCrossValidate, RollingMul)   { check<RollingMulOp>(kMulW3, "rolling_mul(w=3)", 3); }
TEST_F(RollingOpPandasCrossValidate, RollingArgMax) { check<RollingArgMaxOp>(kArgmaxW3, "rolling_argmax(w=3)", 3); }
TEST_F(RollingOpPandasCrossValidate, RollingArgMin) { check<RollingArgMinOp>(kArgminW3, "rolling_argmin(w=3)", 3); }
TEST_F(RollingOpPandasCrossValidate, RollingRank)  { check<RollingRankOp>(kRankW3, "rolling_rank(w=3)", 3); }

// --- Moment statistics ---
TEST_F(RollingOpPandasCrossValidate, RollingSkew)  { check<RollingSkewOp>(kSkewW5, "rolling_skew(w=5)", 5); }
TEST_F(RollingOpPandasCrossValidate, RollingKurt)  { check<RollingKurtOp>(kKurtW5, "rolling_kurt(w=5)", 5); }

// --- Quantile (extra q parameter) ---
TEST_F(RollingOpPandasCrossValidate, RollingQuantile) {
    double output[kN];
    RollingQuantileOp(4, 0.25).evaluate(ColView<double>(kInput, kN), output);
    for (std::size_t i = 0; i < kN; ++i)
        expectDoubleNanEq(output[i], kQuantileQ25W4[i], "rolling_quantile(w=4,q=0.25)", i);

    RollingQuantileOp(4, 0.50).evaluate(ColView<double>(kInput, kN), output);
    for (std::size_t i = 0; i < kN; ++i)
        expectDoubleNanEq(output[i], kQuantileQ50W4[i], "rolling_quantile(w=4,q=0.50)", i);

    RollingQuantileOp(4, 0.75).evaluate(ColView<double>(kInput, kN), output);
    for (std::size_t i = 0; i < kN; ++i)
        expectDoubleNanEq(output[i], kQuantileQ75W4[i], "rolling_quantile(w=4,q=0.75)", i);
}

// --- Moving averages ---
TEST_F(RollingOpPandasCrossValidate, RollingEma) { check<RollingEmaOp>(kEmaW5, "rolling_ema(span=5)", 5); }
TEST_F(RollingOpPandasCrossValidate, RollingSma) { check<RollingSmaOp>(kSmaW3, "rolling_sma(w=3)", 3); }

// --- Lag operators ---
TEST_F(RollingOpPandasCrossValidate, RollingDiff)  { check<RollingDiffOp>(kDiffW3, "rolling_diff(n=3)", 3); }
TEST_F(RollingOpPandasCrossValidate, RollingShift) { check<RollingShiftOp>(kShiftW3, "rolling_shift(n=3)", 3); }

// --- Extra window sizes ---
TEST_F(RollingOpPandasCrossValidate, RollingSumW5) { check<RollingSumOp>(kSumW5, "rolling_sum(w=5)", 5); }
