// alpha_0001.cpp — AOT-compiled factor (auto-generated)
//
// Expression: close / rolling_shift(close, 20) - 1
//
// Generated by: tools/generate_factor.py
// Do not edit by hand.

#include "factors/alpha_0001.h"

#include <cstring>

#include <cmath>
#include <limits>
#include <cstddef>
#include "quantcore/core/Types.h"
#include "quantcore/storage/ColView.h"
#include "quantcore/storage/Column.h"
#include "quantcore/engine/BufferPool.h"
#include "quantcore/engine/ExecutionEngine.h"
#include "quantcore/operators/RollingOperator.h"
#include "quantcore/operators/UnaryOperator.h"
#include "quantcore/operators/BinaryOperator.h"
#include "quantcore/operators/binary/Div.h"
#include "quantcore/operators/rolling/RollingShift.h"
#include "quantcore/operators/binary/Sub.h"

namespace quantcore {
namespace factors {

// ============================================================
// Constants
// ============================================================

const std::string kAlpha0001 = "alpha_0001";

const std::string kAlpha0001Desc =
    "close / rolling_shift(close, 20) - 1";

const std::string kAlpha0001Expr =
    "close / rolling_shift(close, 20) - 1";  // backward compat

// ============================================================
// Core computation
// ============================================================

Column<double> computeAlpha0001(const MarketData& md,
                                            ExecutionEngine& engine) {
    std::size_t n = md.rowCount();
    auto& pool = engine.pool();

    const auto& col0 = md.column<double>(Field::CLOSE);
    const auto& col1 = md.column<double>(Field::CLOSE);
    auto buf0 = pool.allocate<double>(n);
    RollingShiftOp op0(20);
    op0.evaluate(ColView<double>(col1.data(), n), buf0.data());
    auto buf1 = pool.allocate<double>(n);
    DivOp{}.evaluate(Operand(col0.data()), Operand(buf0.data()), buf1.data(), n, nullptr);
    auto buf2 = pool.allocate<double>(n);
    SubOp{}.evaluate(Operand(buf1.data()), Operand(1), buf2.data(), n, nullptr);

    // Materialize final result
    Column<double> result(n);
    std::memcpy(result.data(), buf2.data(), n * sizeof(double));
    return result;
}

// ============================================================
// Registration
// ============================================================

void registerAlpha0001(FactorCalculator& calc) {
    calc.registerCustomFactor(
        kAlpha0001,
        [&calc](const MarketData& md) -> Column<double> {
            return computeAlpha0001(md, calc.engine());
        },
        kAlpha0001Desc);
}

// ============================================================
// Convenience evaluation
// ============================================================

Column<double> evaluateAlpha0001(FactorCalculator& calc,
                                              const MarketData& md) {
    return calc.evaluate(kAlpha0001, md);
}

}  // namespace factors
}  // namespace quantcore
