// alpha_0004.h — AOT-compiled factor (auto-generated)
//
// Expression: abs(close - vwap) / vwap
//
// Generated by: tools/generate_factor.py
// Do not edit by hand — regenerate with:
//   python3 tools/generate_factor.py alpha_0004 "abs(close - vwap) / vwap"
#pragma once

#include <string>
#include "quantcore/core/FactorCalculator.h"
#include "quantcore/storage/Column.h"
#include "quantcore/storage/MarketData.h"

namespace quantcore {
namespace factors {

// ============================================================
// Constants
// ============================================================

extern const std::string kAlpha0004;
extern const std::string kAlpha0004Desc;

// ============================================================
// Core computation (AOT-compiled from expression)
// ============================================================

/// Compute alpha_0004: abs(close - vwap) / vwap
///
/// This function is generated code — no parser, no AST traversal,
/// no virtual dispatch.  All operator calls are direct.
Column<double> computeAlpha0004(const MarketData& md,
                                            ExecutionEngine& engine);

// ============================================================
// Registration
// ============================================================

void registerAlpha0004(FactorCalculator& calc);

// ============================================================
// Convenience evaluation
// ============================================================

Column<double> evaluateAlpha0004(FactorCalculator& calc,
                                              const MarketData& md);

}  // namespace factors
}  // namespace quantcore
