// alpha_0003.cpp — AOT-compiled factor (auto-generated)
//
// Expression: log(close) - log(rolling_shift(close, 1))
//
// Generated by: tools/generate_factor.py
// Do not edit by hand.

#include "factors/alpha_0003.h"

#include <cstring>

#include <cmath>
#include <limits>
#include <cstddef>
#include "quantcore/core/Types.h"
#include "quantcore/storage/ColView.h"
#include "quantcore/storage/Column.h"
#include "quantcore/engine/BufferPool.h"
#include "quantcore/engine/ExecutionEngine.h"
#include "quantcore/operators/RollingOperator.h"
#include "quantcore/operators/UnaryOperator.h"
#include "quantcore/operators/BinaryOperator.h"
#include "quantcore/operators/unary/Log.h"
#include "quantcore/operators/rolling/RollingShift.h"
#include "quantcore/operators/binary/Sub.h"

namespace quantcore {
namespace factors {

// ============================================================
// Constants
// ============================================================

const std::string kAlpha0003 = "alpha_0003";

const std::string kAlpha0003Desc =
    "log(close) - log(rolling_shift(close, 1))";

// ============================================================
// Core computation
// ============================================================

Column<double> computeAlpha0003(const MarketData& md,
                                            ExecutionEngine& engine) {
    std::size_t n = md.rowCount();
    auto& pool = engine.pool();

    const auto& col0 = md.column<double>(Field::CLOSE);
    auto buf0 = pool.allocate<double>(n);
    LogOp{}.evaluate(Operand(col0.data()), buf0.data(), n, nullptr);
    const auto& col1 = md.column<double>(Field::CLOSE);
    auto buf1 = pool.allocate<double>(n);
    RollingShiftOp op0(1);
    op0.evaluate(ColView<double>(col1.data(), n), buf1.data());
    auto buf2 = pool.allocate<double>(n);
    LogOp{}.evaluate(Operand(buf1.data()), buf2.data(), n, nullptr);
    auto buf3 = pool.allocate<double>(n);
    SubOp{}.evaluate(Operand(buf0.data()), Operand(buf2.data()), buf3.data(), n, nullptr);

    // Materialize final result
    Column<double> result(n);
    std::memcpy(result.data(), buf3.data(), n * sizeof(double));
    return result;
}

// ============================================================
// Registration
// ============================================================

void registerAlpha0003(FactorCalculator& calc) {
    calc.registerCustomFactor(
        kAlpha0003,
        [&calc](const MarketData& md) -> Column<double> {
            return computeAlpha0003(md, calc.engine());
        },
        kAlpha0003Desc);
}

// ============================================================
// Convenience evaluation
// ============================================================

Column<double> evaluateAlpha0003(FactorCalculator& calc,
                                              const MarketData& md) {
    return calc.evaluate(kAlpha0003, md);
}

}  // namespace factors
}  // namespace quantcore
