// alpha_0002.cpp — AOT-compiled factor (auto-generated)
//
// Expression: rolling_mean(close, 5) / rolling_mean(close, 20) - 1
//
// Generated by: tools/generate_factor.py
// Do not edit by hand.

#include "factors/alpha_0002.h"

#include <cstring>

#include <cmath>
#include <limits>
#include <cstddef>
#include "quantcore/core/Types.h"
#include "quantcore/storage/ColView.h"
#include "quantcore/storage/Column.h"
#include "quantcore/engine/BufferPool.h"
#include "quantcore/engine/ExecutionEngine.h"
#include "quantcore/operators/RollingOperator.h"
#include "quantcore/operators/UnaryOperator.h"
#include "quantcore/operators/BinaryOperator.h"
#include "quantcore/operators/binary/Div.h"
#include "quantcore/operators/rolling/RollingMean.h"
#include "quantcore/operators/binary/Sub.h"

namespace quantcore {
namespace factors {

// ============================================================
// Constants
// ============================================================

const std::string kAlpha0002 = "alpha_0002";

const std::string kAlpha0002Desc =
    "rolling_mean(close, 5) / rolling_mean(close, 20) - 1";

const std::string kAlpha0002Expr =
    "rolling_mean(close, 5) / rolling_mean(close, 20) - 1";  // backward compat

// ============================================================
// Core computation
// ============================================================

Column<double> computeAlpha0002(const MarketData& md,
                                            ExecutionEngine& engine) {
    std::size_t n = md.rowCount();
    auto& pool = engine.pool();

    const auto& col0 = md.column<double>(Field::CLOSE);
    auto buf0 = pool.allocate<double>(n);
    RollingMeanOp op0(5);
    op0.evaluate(ColView<double>(col0.data(), n), buf0.data());
    const auto& col1 = md.column<double>(Field::CLOSE);
    auto buf1 = pool.allocate<double>(n);
    RollingMeanOp op1(20);
    op1.evaluate(ColView<double>(col1.data(), n), buf1.data());
    auto buf2 = pool.allocate<double>(n);
    DivOp{}.evaluate(Operand(buf0.data()), Operand(buf1.data()), buf2.data(), n, nullptr);
    auto buf3 = pool.allocate<double>(n);
    SubOp{}.evaluate(Operand(buf2.data()), Operand(1), buf3.data(), n, nullptr);

    // Materialize final result
    Column<double> result(n);
    std::memcpy(result.data(), buf3.data(), n * sizeof(double));
    return result;
}

// ============================================================
// Registration
// ============================================================

void registerAlpha0002(FactorCalculator& calc) {
    calc.registerCustomFactor(
        kAlpha0002,
        [&calc](const MarketData& md) -> Column<double> {
            return computeAlpha0002(md, calc.engine());
        },
        kAlpha0002Desc);
}

// ============================================================
// Convenience evaluation
// ============================================================

Column<double> evaluateAlpha0002(FactorCalculator& calc,
                                              const MarketData& md) {
    return calc.evaluate(kAlpha0002, md);
}

}  // namespace factors
}  // namespace quantcore
