// alpha_0005.h — AOT-compiled factor (auto-generated)
//
// Expression: rolling_std(log(close) - log(rolling_shift(close, 1)), 20)
//
// Generated by: tools/generate_factor.py
// Do not edit by hand — regenerate with:
//   python3 tools/generate_factor.py alpha_0005 "rolling_std(log(close) - log(rolling_shift(close, 1)), 20)"
#pragma once

#include <string>
#include "quantcore/core/FactorCalculator.h"
#include "quantcore/storage/Column.h"
#include "quantcore/storage/MarketData.h"

namespace quantcore {
namespace factors {

// ============================================================
// Constants
// ============================================================

extern const std::string kAlpha0005;
extern const std::string kAlpha0005Desc;

// ============================================================
// Core computation (AOT-compiled from expression)
// ============================================================

/// Compute alpha_0005: rolling_std(log(close) - log(rolling_shift(close, 1)), 20)
///
/// This function is generated code — no parser, no AST traversal,
/// no virtual dispatch.  All operator calls are direct.
Column<double> computeAlpha0005(const MarketData& md,
                                            ExecutionEngine& engine);

// ============================================================
// Registration
// ============================================================

void registerAlpha0005(FactorCalculator& calc);

// ============================================================
// Convenience evaluation
// ============================================================

Column<double> evaluateAlpha0005(FactorCalculator& calc,
                                              const MarketData& md);

}  // namespace factors
}  // namespace quantcore
