// alpha_0003.h — AOT-compiled factor (auto-generated)
//
// Expression: log(close) - log(rolling_shift(close, 1))
//
// Generated by: tools/generate_factor.py
// Do not edit by hand — regenerate with:
//   python3 tools/generate_factor.py alpha_0003 "log(close) - log(rolling_shift(close, 1))"
#pragma once

#include <string>
#include "quantcore/core/FactorCalculator.h"
#include "quantcore/storage/Column.h"
#include "quantcore/storage/MarketData.h"

namespace quantcore {
namespace factors {

// ============================================================
// Constants
// ============================================================

extern const std::string kAlpha0003;
extern const std::string kAlpha0003Desc;

// ============================================================
// Core computation (AOT-compiled from expression)
// ============================================================

/// Compute alpha_0003: log(close) - log(rolling_shift(close, 1))
///
/// This function is generated code — no parser, no AST traversal,
/// no virtual dispatch.  All operator calls are direct.
Column<double> computeAlpha0003(const MarketData& md,
                                            ExecutionEngine& engine);

// ============================================================
// Registration
// ============================================================

void registerAlpha0003(FactorCalculator& calc);

// ============================================================
// Convenience evaluation
// ============================================================

Column<double> evaluateAlpha0003(FactorCalculator& calc,
                                              const MarketData& md);

}  // namespace factors
}  // namespace quantcore
