// alpha_0004.cpp — AOT-compiled factor (auto-generated)
//
// Expression: abs(close - vwap) / vwap
//
// Generated by: tools/generate_factor.py
// Do not edit by hand.

#include "factors/alpha_0004.h"

#include <cstring>

#include <cmath>
#include <limits>
#include <cstddef>
#include "quantcore/core/Types.h"
#include "quantcore/storage/ColView.h"
#include "quantcore/storage/Column.h"
#include "quantcore/engine/BufferPool.h"
#include "quantcore/engine/ExecutionEngine.h"
#include "quantcore/operators/RollingOperator.h"
#include "quantcore/operators/UnaryOperator.h"
#include "quantcore/operators/BinaryOperator.h"
#include "quantcore/operators/unary/Abs.h"
#include "quantcore/operators/binary/Div.h"
#include "quantcore/operators/binary/Sub.h"

namespace quantcore {
namespace factors {

// ============================================================
// Constants
// ============================================================

const std::string kAlpha0004 = "alpha_0004";

const std::string kAlpha0004Desc =
    "abs(close - vwap) / vwap";

// ============================================================
// Core computation
// ============================================================

Column<double> computeAlpha0004(const MarketData& md,
                                            ExecutionEngine& engine) {
    std::size_t n = md.rowCount();
    auto& pool = engine.pool();

    const auto& col0 = md.column<double>(Field::CLOSE);
    const auto& col1 = md.column<double>(Field::VWAP);
    auto buf0 = pool.allocate<double>(n);
    SubOp{}.evaluate(Operand(col0.data()), Operand(col1.data()), buf0.data(), n, nullptr);
    auto buf1 = pool.allocate<double>(n);
    AbsOp{}.evaluate(Operand(buf0.data()), buf1.data(), n, nullptr);
    const auto& col2 = md.column<double>(Field::VWAP);
    auto buf2 = pool.allocate<double>(n);
    DivOp{}.evaluate(Operand(buf1.data()), Operand(col2.data()), buf2.data(), n, nullptr);

    // Materialize final result
    Column<double> result(n);
    std::memcpy(result.data(), buf2.data(), n * sizeof(double));
    return result;
}

// ============================================================
// Registration
// ============================================================

void registerAlpha0004(FactorCalculator& calc) {
    calc.registerCustomFactor(
        kAlpha0004,
        [&calc](const MarketData& md) -> Column<double> {
            return computeAlpha0004(md, calc.engine());
        },
        kAlpha0004Desc);
}

// ============================================================
// Convenience evaluation
// ============================================================

Column<double> evaluateAlpha0004(FactorCalculator& calc,
                                              const MarketData& md) {
    return calc.evaluate(kAlpha0004, md);
}

}  // namespace factors
}  // namespace quantcore
