// alpha_0001.h — AOT-compiled factor (auto-generated)
//
// Expression: close / rolling_shift(close, 20) - 1
//
// Generated by: tools/generate_factor.py
// Do not edit by hand — regenerate with:
//   python3 tools/generate_factor.py alpha_0001 "close / rolling_shift(close, 20) - 1"
#pragma once

#include <string>
#include "quantcore/core/FactorCalculator.h"
#include "quantcore/storage/Column.h"
#include "quantcore/storage/MarketData.h"

namespace quantcore {
namespace factors {

// ============================================================
// Constants
// ============================================================

extern const std::string kAlpha0001;
extern const std::string kAlpha0001Desc;
extern const std::string kAlpha0001Expr;  // backward compat: expression string

// ============================================================
// Core computation (AOT-compiled from expression)
// ============================================================

/// Compute alpha_0001: close / rolling_shift(close, 20) - 1
///
/// This function is generated code — no parser, no AST traversal,
/// no virtual dispatch.  All operator calls are direct.
Column<double> computeAlpha0001(const MarketData& md,
                                            ExecutionEngine& engine);

// ============================================================
// Registration
// ============================================================

void registerAlpha0001(FactorCalculator& calc);

// ============================================================
// Convenience evaluation
// ============================================================

Column<double> evaluateAlpha0001(FactorCalculator& calc,
                                              const MarketData& md);

}  // namespace factors
}  // namespace quantcore
