// test_alpha_0003_0005.cpp — integration tests for alpha_0003, alpha_0004, alpha_0005
//
// These factors are AOT-compiled (generated by tools/generate_factor.py).
// Tests validate correctness against hand-computed expected values.
#include <gtest/gtest.h>
#include <cmath>
#include <limits>
#include <vector>

#include "factors/alpha_0003.h"
#include "factors/alpha_0004.h"
#include "factors/alpha_0005.h"
#include "quantcore/core/FactorCalculator.h"
#include "quantcore/core/Types.h"
#include "quantcore/storage/MarketData.h"
#include "quantcore/storage/TimestampIndex.h"

using namespace quantcore;

class GeneratedFactorsTest : public ::testing::Test {
protected:
    static constexpr std::size_t kN = 10;

    void SetUp() override {
        // Build timestamp index
        std::vector<int64_t> timestamps(kN);
        for (std::size_t i = 0; i < kN; ++i)
            timestamps[i] = static_cast<int64_t>(20200101 + i);
        TimestampIndex tsIdx(timestamps.data(), kN);
        md_ = MarketData("TEST", std::move(tsIdx));

        // Fill fields with known values:
        //   close: 100, 101, 102, 101, 103, 105, 104, 106, 108, 107
        //   vwap:   99, 101, 103, 100, 104, 106, 103, 107, 109, 106
        for (std::size_t f = 0; f < static_cast<std::size_t>(Field::kFieldCount); ++f) {
            auto field = static_cast<Field>(f);
            Column<double> col(kN);
            for (std::size_t i = 0; i < kN; ++i) {
                switch (field) {
                    case Field::CLOSE:
                        col[i] = close_[i]; break;
                    case Field::VWAP:
                        col[i] = vwap_[i]; break;
                    default:
                        col[i] = static_cast<double>(i); break;
                }
            }
            md_.setColumn(field, std::move(col));
        }
    }

    // Expected data
    const std::vector<double> close_ = {100, 101, 102, 101, 103, 105, 104, 106, 108, 107};
    const std::vector<double> vwap_  = { 99, 101, 103, 100, 104, 106, 103, 107, 109, 106};
    MarketData md_;
};

// ============================================================
// alpha_0003: log(close) - log(rolling_shift(close, 1))
// 1-day log return: ln(close[i]) - ln(close[i-1])
// ============================================================

TEST_F(GeneratedFactorsTest, Alpha0003LogReturn) {
    FactorCalculator calc;
    factors::registerAlpha0003(calc);
    auto result = calc.evaluate("alpha_0003", md_);

    ASSERT_EQ(result.size(), kN);

    // i=0: NaN (rolling_shift with window=1 → first element is NaN)
    EXPECT_TRUE(std::isnan(result[0]));

    // i=1: ln(101) - ln(100)
    double expected = std::log(101.0) - std::log(100.0);
    EXPECT_NEAR(result[1], expected, 1e-12);

    // i=2: ln(102) - ln(101)
    expected = std::log(102.0) - std::log(101.0);
    EXPECT_NEAR(result[2], expected, 1e-12);

    // i=9: ln(107) - ln(108) (negative log return)
    expected = std::log(107.0) - std::log(108.0);
    EXPECT_NEAR(result[9], expected, 1e-12);
}

TEST_F(GeneratedFactorsTest, Alpha0003ConvenienceFn) {
    FactorCalculator calc;
    // evaluateAlpha0003 requires prior registration
    factors::registerAlpha0003(calc);
    auto result = factors::evaluateAlpha0003(calc, md_);

    ASSERT_EQ(result.size(), kN);
    EXPECT_TRUE(std::isnan(result[0]));
    double expected = std::log(101.0) - std::log(100.0);
    EXPECT_NEAR(result[1], expected, 1e-12);
}

// ============================================================
// alpha_0004: abs(close - vwap) / vwap
// ============================================================

TEST_F(GeneratedFactorsTest, Alpha0004VwapDeviation) {
    FactorCalculator calc;
    factors::registerAlpha0004(calc);
    auto result = calc.evaluate("alpha_0004", md_);

    ASSERT_EQ(result.size(), kN);

    // i=0: abs(100 - 99) / 99 = 1/99 ≈ 0.010101
    double expected = std::abs(close_[0] - vwap_[0]) / vwap_[0];
    EXPECT_NEAR(result[0], expected, 1e-12);

    // i=3: abs(101 - 100) / 100 = 0.01
    expected = std::abs(close_[3] - vwap_[3]) / vwap_[3];
    EXPECT_NEAR(result[3], expected, 1e-12);

    // i=8: abs(108 - 109) / 109 = 1/109
    expected = std::abs(close_[8] - vwap_[8]) / vwap_[8];
    EXPECT_NEAR(result[8], expected, 1e-12);

    // Check all positions
    for (std::size_t i = 0; i < kN; ++i) {
        expected = std::abs(close_[i] - vwap_[i]) / vwap_[i];
        EXPECT_NEAR(result[i], expected, 1e-12) << "i=" << i;
    }
}

// ============================================================
// alpha_0005: rolling_std(log(close) - log(rolling_shift(close, 1)), 20)
// 20-day rolling volatility of daily log returns.
// With window=20 and only 10 rows, all positions are NaN.
// ============================================================

TEST_F(GeneratedFactorsTest, Alpha0005AllNanSmallWindow) {
    FactorCalculator calc;
    factors::registerAlpha0005(calc);
    auto result = calc.evaluate("alpha_0005", md_);

    ASSERT_EQ(result.size(), kN);
    // All NaN: window=20 but only 10 data points
    for (std::size_t i = 0; i < kN; ++i) {
        EXPECT_TRUE(std::isnan(result[i])) << "i=" << i;
    }
}

// ============================================================
// Additional: verify that computeAlpha0005 works with enough data
// ============================================================

TEST_F(GeneratedFactorsTest, Alpha0005ComputeDirect) {
    // Create a dataset with constant daily log returns (geometric price series).
    // close[i] = 100 * 1.01^i  →  ln(close[i]) = ln(100) + i*ln(1.01)
    // 1-day log return = ln(1.01) = constant for all i
    // rolling_std of constant values = 0 for all windows
    std::size_t bigN = 30;
    const double growth = 1.01;
    const double logGrowth = std::log(growth);

    std::vector<int64_t> timestamps(bigN);
    for (std::size_t i = 0; i < bigN; ++i)
        timestamps[i] = static_cast<int64_t>(i);
    TimestampIndex tsIdx(timestamps.data(), bigN);
    MarketData bigMd("GEO", std::move(tsIdx));

    Column<double> close(bigN);
    close[0] = 100.0;
    for (std::size_t i = 1; i < bigN; ++i)
        close[i] = close[i - 1] * growth;
    bigMd.setColumn(Field::CLOSE, std::move(close));

    // Fill remaining fields with dummy data
    for (auto f : {Field::OPEN, Field::HIGH, Field::LOW, Field::VWAP,
                   Field::VOLUME, Field::AMOUNT}) {
        Column<double> col(bigN);
        for (std::size_t i = 0; i < bigN; ++i)
            col[i] = static_cast<double>(i);
        bigMd.setColumn(f, std::move(col));
    }

    FactorCalculator calc;
    factors::registerAlpha0005(calc);
    auto result = calc.evaluate("alpha_0005", bigMd);

    ASSERT_EQ(result.size(), bigN);

    // First 20 positions: NaN (window=20 + log_ret[0] is NaN)
    for (std::size_t i = 0; i < 20; ++i) {
        EXPECT_TRUE(std::isnan(result[i])) << "i=" << i;
    }

    // Positions 20+: window [1..20] skips the NaN at position 0
    // constant log returns → rolling_std ≈ 0
    for (std::size_t i = 20; i < bigN; ++i) {
        EXPECT_FALSE(std::isnan(result[i])) << "i=" << i;
        EXPECT_GE(result[i], 0.0) << "i=" << i;
        EXPECT_NEAR(result[i], 0.0, 1e-10) << "i=" << i;
    }
}
